(Fanuc 30im ini file)

( *** MACHINE PARAMETERS *** )
CGTech_Var NCK STRING Mapping = "1 2 3 4 5 6 7 8 9"
CGTech_Var NCK STRING Mapp[13]
CGTech_Var NCK REAL Axis[13]
CGTech_Var NCK INT MP_00000[8]
CGTech_Var NCK INT MP_01006[16]
CGTech_Var NCK INT MP_01008[16]
CGTech_Var NCK INT MP_01205[8]
CGTech_Var NCK REAL MP_01240[12]
CGTech_Var NCK REAL MP_01241[12]
CGTech_Var NCK REAL MP_01242[12]
CGTech_Var NCK REAL MP_01243[12]
CGTech_Var NCK REAL MP_01320[12]
CGTech_Var NCK REAL MP_01321[12]
CGTech_Var NCK INT MP_01401[8]
CGTech_Var NCK REAL MP_01420[12]
CGTech_Var NCK REAL MP_01430[12]
CGTech_Var NCK REAL MP_01432[12]
CGTech_Var NCK INT MP_03401[8]
CGTech_Var NCK INT MP_03402[8]
CGTech_Var NCK INT MP_03403[8]
CGTech_Var NCK REAL MP_03410
CGTech_Var NCK INT MP_05006[8]
CGTech_Var NCK INT MP_05400[8]
CGTech_Var NCK REAL MP_05410 = 0
CGTech_Var NCK INT MP_05114[8]
CGTech_Var NCK INT MP_11221[8]
CGTech_Var NCK INT MP_11600[8]
CGTech_Var NCK INT MP_19680
CGTech_Var NCK INT MP_19681
CGTech_Var NCK INT MP_19682
CGTech_Var NCK INT MP_19683
CGTech_Var NCK INT MP_19684
CGTech_Var NCK INT MP_19686
CGTech_Var NCK INT MP_19687
CGTech_Var NCK INT MP_19688
CGTech_Var NCK INT MP_19689
CGTech_Var NCK INT MP_19691
CGTech_Var NCK INT MP_19692
CGTech_Var NCK INT MP_19696[8]
CGTech_Var NCK INT MP_19700
CGTech_Var NCK INT MP_19701
CGTech_Var NCK INT MP_19702
CGTech_Var NCK INT MP_19703
CGTech_Var NCK INT MP_19704
CGTech_Var NCK INT MP_19705
( *** MACHINE PARAMETERS *** )

(Machine Parameters Comments)
CGTech_Macro "AddCommentToVar" "Mapping Default Axis Order"
CGTech_Macro "AddCommentToVar" "MP_00000 00000.2 0=metric input 1=inch input"
CGTech_Macro "AddCommentToVar" "MP_01006 1006.0 ROTx and 1006.1 ROSx EIA or Linear 1006.3 Dia or Rad"
CGTech_Macro "AddCommentToVar" "MP_01008 1008.0 ROAx rotary rollover 1008.1 RABx shortest distance"
CGTech_Macro "AddCommentToVar" "MP_01205 1205.6 = 0 Alarm PS5462 if a work offset is programmed during TWP G68.2"
CGTech_Macro "AddCommentToVar" "MP_01240 G28 position"
CGTech_Macro "AddCommentToVar" "MP_01241 G30 P2 position"
CGTech_Macro "AddCommentToVar" "MP_01242 G30 P3 position"
CGTech_Macro "AddCommentToVar" "MP_01243 G30 P4 position"
CGTech_Macro "AddCommentToVar" "MP_01320 Travel limits +"
CGTech_Macro "AddCommentToVar" "MP_01321 Travel limits -"
CGTech_Macro "AddCommentToVar" "MP_01401 1401.1 = 1 Linear interpolation in G0, 0 = non linear in G0, Dogleg in rapid"
CGTech_Macro "AddCommentToVar" "MP_01420 Rapid traverse rate for each axis"
CGTech_Macro "AddCommentToVar" "MP_01430 Max feed rate for each axis"
CGTech_Macro "AddCommentToVar" "MP_01432 Max feed rate for each axis if G5 P10000 / G8 P1 look ahead is used"
CGTech_Macro "AddCommentToVar" "MP_03401 3401.0 Decimal point programming 0: 1=1 micron 1: 1=1mm"
CGTech_Macro "AddCommentToVar" "MP_03402 Power on defaults for G0/G1 G17/G18 G19 G90/G91 FPM/FPR G70/71/G20/G21"
CGTech_Macro "AddCommentToVar" "MP_03403 3403.5 = 0 G2/3 motion is STRAIGHT LINE if no IJK or R present, 1 = An alarm PS0022, “R OR I,J,K COMMAND NOT FOUND�? is issued"
CGTech_Macro "AddCommentToVar" "MP_03410 Tolerance of arc radius between start and end point"
CGTech_Macro "AddCommentToVar" "MP_05006 5006.6 = 1 TLC no motion for G43 G49"
CGTech_Macro "AddCommentToVar" "MP_05114 5114.2 = Retract distance during peck drilling G83"
CGTech_Macro "AddCommentToVar" "MP_05400 5400.0 G68 Coordinate Rotation angle defaults to absolute"
CGTech_Macro "AddCommentToVar" "MP_05410 5410 = G68 default value when R is not programmed"
CGTech_Macro "AddCommentToVar" "MP_11221 11211.0 = 1 Multiple TWP commands are allowed 'G68.2' 11221.4 = 1 Rotate rotary axes to B0 C0 but Xcmd moves in +X direction /  Ycmd moves in +Y direction"
CGTech_Macro "AddCommentToVar" "MP_11600 11600.5 = 0 G68 rotation is calculated before coordinate system is rotated
CGTech_Macro "AddCommentToVar" "MP_19680 Mechanical unit type 0 = No rotaries 2 = Tool rotation 2 axes 12 = Table rotation 2 axes 21 = Mixed 2 axes"
CGTech_Macro "AddCommentToVar" "MP_19681 Controlled axis number for the first rotation axis"
CGTech_Macro "AddCommentToVar" "MP_19682 Axis direction of the first rotation axis, does it rotate around X or Y or Z"
CGTech_Macro "AddCommentToVar" "MP_19683 Inclination angle when the first rotation axis is inclined"
CGTech_Macro "AddCommentToVar" "MP_19684 Rotation direction of the first rotation axis, which way is CW & CCW"
CGTech_Macro "AddCommentToVar" "MP_19686 Controlled axis number for the second rotation axis"
CGTech_Macro "AddCommentToVar" "MP_19687 Axis direction of the second rotation axis, does it rotate around X or Y or Z"
CGTech_Macro "AddCommentToVar" "MP_19688 Inclination angle when the second rotation axis is inclined"
CGTech_Macro "AddCommentToVar" "MP_19689 Rotation direction of the second rotation axis, which way is CW & CCW"
CGTech_Macro "AddCommentToVar" "MP_19691 Controlled axis number for the third rotation axis"
CGTech_Macro "AddCommentToVar" "MP_19692 Axis direction of the third rotation axis, does it rotate around X or Y or Z"
CGTech_Macro "AddCommentToVar" "MP_19696 19696.5 Coordinate system is in 0 :table coords  1: machine ( Fanuc Workpiece )"
CGTech_Macro "AddCommentToVar" "MP_19700 Rotary table position ( X axis )"
CGTech_Macro "AddCommentToVar" "MP_19701 Rotary table position ( Y axis )"
CGTech_Macro "AddCommentToVar" "MP_19702 Rotary table position ( Z axis )"
CGTech_Macro "AddCommentToVar" "MP_19703 Intersection offset between first and second rotaries in X"
CGTech_Macro "AddCommentToVar" "MP_19704 Intersection offset between first and second rotaries in Y"
CGTech_Macro "AddCommentToVar" "MP_19705 Intersection offset between first and second rotaries in Z"

( *** THESE MACHINE PARAMETERS NEED TO BE NULL BY DEFAULT *** )
CGTECH_MACRO "NCVarDefaultValue" "" 1

#1=0
WHILE [#1 LT 8] DO1
MP_00000[#1] = #0
#1=#1+1
END1

#1=0
WHILE [#1 LT 16] DO1
MP_01006[#1] = #0
#1=#1+1
END1

#1=0
WHILE [#1 LT 16] DO1
MP_01008[#1] = #0
#1=#1+1
END1

#1=0
WHILE [#1 LT 8] DO1
MP_01205[#1] = #0
#1=#1+1
END1

#1=0
WHILE [#1 LT 12] DO1
MP_01240[#1] = #0
#1=#1+1
END1

#1=0
WHILE [#1 LT 12] DO1
MP_01241[#1] = #0
#1=#1+1
END1

#1=0
WHILE [#1 LT 12] DO1
MP_01242[#1] = #0
#1=#1+1
END1

#1=0
WHILE [#1 LT 12] DO1
MP_01243[#1] = #0
#1=#1+1
END1

#1=0
WHILE [#1 LT 12] DO1
MP_01320[#1] = #0
#1=#1+1
END1

#1=0
WHILE [#1 LT 12] DO1
MP_01321[#1] = #0
#1=#1+1
END1

#1=0
WHILE [#1 LT 8] DO1
MP_01401[#1] = #0
#1=#1+1
END1

#1=0
WHILE [#1 LT 12] DO1
MP_01420[#1] = #0
#1=#1+1
END1

#1=0
WHILE [#1 LT 12] DO1
MP_01430[#1] = #0
#1=#1+1
END1

#1=0
WHILE [#1 LT 12] DO1
MP_01432[#1] = #0
#1=#1+1
END1

#1=0
WHILE [#1 LT 8] DO1
MP_03401[#1] = #0
#1=#1+1
END1

#1=0
WHILE [#1 LT 8] DO1
MP_03402[#1] = #0
#1=#1+1
END1

#1=0
WHILE [#1 LT 8] DO1
MP_03403[#1] = #0
#1=#1+1
END1

MP_03410=#0

#1=0
WHILE [#1 LT 8] DO1
MP_05006[#1] = #0
#1=#1+1
END1

#1=0
WHILE [#1 LT 8] DO1
MP_05114[#1] = #0
#1=#1+1
END1

#1=0
WHILE [#1 LT 8] DO1
MP_05400[#1] = #0
#1=#1+1
END1

#1=0
WHILE [#1 LT 8] DO1
MP_11221[#1] = #0
#1=#1+1
END1

#1=0
WHILE [#1 LT 8] DO1
MP_11600[#1] = #0
#1=#1+1
END1
  
MP_19680=#0
MP_19681=#0
MP_19682=#0
MP_19683=#0
MP_19684=#0
MP_19686=#0
MP_19687=#0
MP_19688=#0
MP_19689=#0
MP_19691=#0
MP_19692=#0

#1=0
WHILE [#1 LT 8] DO1
MP_19696[#1] = #0
#1=#1+1
END1
#1=#0

MP_19700=#0
MP_19701=#0
MP_19702=#0
MP_19703=#0
MP_19704=#0
MP_19705=#0 





CGTECH_MACRO "NCVarDefaultValue" "" 0
( *** THESE MACHINE PARAMETERS NEED TO BE NULL BY DEFAULT *** )


( *** GLOBAL SETTINGS *** )

CGTECH_MACRO "GlobalVariables" "3001-3002"
CGTECH_MACRO "VariableAlias" "3001,_CLOCK1"
CGTECH_MACRO "VariableAlias" "3002,_CLOCK2"

( *** SUBSYSTEM 1 *** )

CGTECH_MACRO "SetSubsystemID" "1"
CGTECH_MACRO "VariableAlias" "0,_EMPTY"


( *** DEFAULT ON POWER ON *** )
#4001=0
#4002=17
#4003=90
#4005=94
#4006=20
#4007=40
#4008=49
#4009=80
#4010=98
#4014=54
#4018=50.1
#5500=0

MP_05400[0] = 0 (G68 Coordinate Rotation angle defaults to absolute)
MP_11600[5] = 0 (G68 Coordinate is calculated before rotation)

( *** DEFAULT ON POWER ON *** )


( *** G54.4 P1-P7 DEFAULT TO 0 *** )
CGTECH_VAR CHAN INT CGT_G54.4_PNO 0
(ZERO G54.4 COMMON) 
#26000=0(X SHIFT) 
#26001=0(Y SHIFT) 
#26002=0(Z SHIFT) 
#26006=0(FIRST ROTARY AXIS)
#26007=0(SECOND ROTARY AXIS)

(ZERO G54.4 P1) 
#26010=0(X SHIFT) 
#26011=0(Y SHIFT) 
#26012=0(Z SHIFT) 
#26013=0(a ROT) 
#26014=0(b ROT) 
#26015=0(c ROT) 
#26016=0(FIRST ROTARY AXIS)
#26017=0(SECOND ROTARY AXIS)

(ZERO G54.4 P2) 
#26020=0(X SHIFT) 
#26021=0(Y SHIFT) 
#26022=0(Z SHIFT) 
#26023=0(a ROT) 
#26024=0(b ROT) 
#26025=0(c ROT) 
#26026=0(FIRST ROTARY AXIS)
#26027=0(SECOND ROTARY AXIS)

(ZERO G54.4 P3) 
#26030=0(X SHIFT) 
#26031=0(Y SHIFT) 
#26032=0(Z SHIFT) 
#26033=0(a ROT) 
#26034=0(b ROT) 
#26035=0(c ROT) 
#26036=0(FIRST ROTARY AXIS)
#26037=0(SECOND ROTARY AXIS)

(ZERO G54.4 P4) 
#26040=0(X SHIFT) 
#26041=0(Y SHIFT) 
#26042=0(Z SHIFT) 
#26043=0(a ROT) 
#26044=0(b ROT) 
#26045=0(c ROT) 
#26046=0(FIRST ROTARY AXIS)
#26047=0(SECOND ROTARY AXIS)

(ZERO G54.4 P5) 
#26050=0(X SHIFT) 
#26051=0(Y SHIFT) 
#26052=0(Z SHIFT) 
#26053=0(a ROT) 
#26054=0(b ROT) 
#26055=0(c ROT) 
#26056=0(FIRST ROTARY AXIS)
#26057=0(SECOND ROTARY AXIS)

(ZERO G54.4 P6) 
#26060=0(X SHIFT) 
#26061=0(Y SHIFT) 
#26062=0(Z SHIFT) 
#26063=0(a ROT) 
#26064=0(b ROT) 
#26065=0(c ROT) 
#26066=0(FIRST ROTARY AXIS)
#26067=0(SECOND ROTARY AXIS)

(ZERO G54.4 P7) 
#26070=0(X SHIFT) 
#26071=0(Y SHIFT) 
#26072=0(Z SHIFT) 
#26073=0(a ROT) 
#26074=0(b ROT) 
#26075=0(c ROT) 
#26076=0(FIRST ROTARY AXIS)
#26077=0(SECOND ROTARY AXIS)
( *** G54.4 P1-P7 DEFAULT TO 0 *** )


( *** VARIABLE ALIAS *** )
CGTECH_MACRO "VariableArrayAlias" "2001,_OFSHG,200"
CGTECH_MACRO "VariableArrayAlias" "2201,_OFSHW,200"
CGTECH_MACRO "VariableArrayAlias" "2401,_OFSDG,200"
CGTECH_MACRO "VariableArrayAlias" "2601,_OFSDW,200"
CGTECH_MACRO "VariableArrayAlias" "4001,_BUFG,33"
CGTECH_MACRO "VariableAlias" "4102,_BUFB"
CGTECH_MACRO "VariableAlias" "4107,_BUFD"
CGTECH_MACRO "VariableAlias" "4109,_BUFF"
CGTECH_MACRO "VariableAlias" "4111,_BUFH"
CGTECH_MACRO "VariableAlias" "4113,_BUFM"
CGTECH_MACRO "VariableAlias" "4114,_BUFN"
CGTECH_MACRO "VariableAlias" "4115,_BUFO"
CGTECH_MACRO "VariableAlias" "4119,_BUFS"
CGTECH_MACRO "VariableAlias" "4120,_BUFT"
CGTECH_MACRO "VariableAlias" "4130,_BUFWZP"
CGTECH_MACRO "VariableArrayAlias" "4201,_ACTG,33"
CGTECH_MACRO "VariableAlias" "4302,_ACTB"
CGTECH_MACRO "VariableAlias" "4307,_ACTD"
CGTECH_MACRO "VariableAlias" "4308,_ACTE"
CGTECH_MACRO "VariableAlias" "4309,_ACTF"
CGTECH_MACRO "VariableAlias" "4311,_ACTH"
CGTECH_MACRO "VariableAlias" "4313,_ACTN"
CGTECH_MACRO "VariableAlias" "4314,_ACTN"
CGTECH_MACRO "VariableAlias" "4315,_ACTO"
CGTECH_MACRO "VariableAlias" "4319,_ACTS"
CGTECH_MACRO "VariableAlias" "4320,_ACTT"
CGTECH_MACRO "VariableAlias" "4330,_ACTWZP"


( *** WORK OFFSETS G54-G59 ***)
CGTECH_MACRO "VariableArrayAlias" "5221,_WZG54,20"
CGTECH_MACRO "VariableArrayAlias" "5241,_WZG55,20"
CGTECH_MACRO "VariableArrayAlias" "5261,_WZG56,20"
CGTECH_MACRO "VariableArrayAlias" "5281,_WZG57,20"
CGTECH_MACRO "VariableArrayAlias" "5301,_WZG58,20"
CGTECH_MACRO "VariableArrayAlias" "5321,_WZG59,20"
CGTECH_MACRO "VariableArrayAlias" "5001,_ABSIO,20"
CGTECH_MACRO "VariableArrayAlias" "5021,_ABSMT,20"
CGTECH_MACRO "VariableArrayAlias" "5041,_ABSOT,20"



CGTECH_MACRO "VariableArrayAlias" "100351,_WZG54,50"
CGTECH_MACRO "VariableArrayAlias" "100401,_WZG55,50"
CGTECH_MACRO "VariableArrayAlias" "100451,_WZG56,50"
CGTECH_MACRO "VariableArrayAlias" "100501,_WZG57,50"
CGTECH_MACRO "VariableArrayAlias" "100551,_WZG58,50"
CGTECH_MACRO "VariableArrayAlias" "100601,_WZG59,50"


CGTECH_MACRO "RestoreSetSubsystemID"


